# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160303_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myimage', models.ImageField(blank=True, upload_to='images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blog.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
