# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160303_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetopost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
