# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160303_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetopost',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImageToPost',
        ),
    ]
